### ISSUE TITLE
Jittery camera movement on tilemaps.

### ISSUE THREAD

**Issue by ghost** [flixel-gdx/flixel-gdx#30]
There is a weird sight when you have a moving camera (i.e. following the player), a "FlxTilemap" and a couple of "FlxSprites", you should notice a slight jittering that feels like "FlxSprites" are moving back-and forth in a distance like a pixel. Jitter's movement direction is related with camera's current direction and speed. I think it's a problem caused by FlxTilemap's rendering functions. Because when only placing a "FlxTileblock" and and "FlxSprite"s in same situation, this scenario does not occur. "Mode" example is working fine because it's using "FlxTileblock"s. I'm not pro in low-level stuff but this may be caused by a rounding error or a problem in rendering phase but I couldn't figure out where.

Happened on Desktop and Android (Galaxy S4).

**Comment by Rombusevil** [comment]
I'm encountering this problem in the current stable release.
I believe it's because of the int casts in FlxTilemap _point.x and _point.y.
I've tested it without casting to int and works great, but it makes me wonder the reason of those casts to be there and if it's safe to remove them.

Also, this is noticeable with low resolution games. Such as 64x64px on a 512x512px window with tiles of 16x16px

**Comment by kamstrup** [comment]
Noticed this as well. Do you have a patch @Rombusevil ?

**Comment by Rombusevil** [comment]
@kamstrup I'll try to make a pull request with FlxTilemap class without those int casts I was talking about. I believe those are safe to remove and have tested that actually improve the smoothness of the camera movement.

**Comment by Rombusevil** [comment]
I'm not exactly sure how to proceed. Removing int casts in position variable definitively improves the behavior but if you move fast you see what it seems to be a scan line. Still I think it's better than having the map  trembling around. 

I leave a patch, @kamstrup  would you help me test it?  For what I can tell in a low resolution game it works fine (you can check it here by downloading both versions of this game https://goo.gl/PgmxJG one trembling and the other one smoother with the fix)

[JitteryTilemap.patch.zip](https://github.com/flixel-gdx/flixel-gdx/files/256186/JitteryTilemap.patch.zip)

**Comment by moly** [comment]
@Rombusevil 

Thanks for the patch. I've applied it, and removed some additional int casts elsewhere, and the movement now seems a lot better. This fix should now be available on the master branch,

**Comment by Rombusevil** [comment]
@moly That's great! thanks man! I just updated my project to the latest version and it's working as expected B-)
