### ISSUE TITLE
setVolume in FlxSound not working

### ISSUE THREAD

**Issue by iainheng** [flixel-gdx/flixel-gdx#69]
I tried set volume of my sound fx with the following code 
```
FlxSound sndStep = FlxSound().loadEmbedded(Assets.sndFootstep1, false, false, FlxSound.SFX);
sndStep.setVolume(0.1f);
```
But the sound volume is not changed no matter what value I passed in.

**Comment by moly** [comment]
This should hopefully now be fixed.

**Comment by Rombusevil** [comment]
This is not fixed. I'm having the same issue. I set volume to 0 and it sounds the same as with setVolume(1)
