### ISSUE TITLE
Android: how to use the Back button?

### ISSUE THREAD

**Issue by peterwilli** [flixel-gdx/flixel-gdx#83]
Hi,

I would like to let users go back to the menu when they press the back button, instead of closing the whole game. I can't find out how to do this.

Does anyone know? Thanks!

**Comment by moly** [comment]
Hi,

You need to call [Gdx.input.setCatchBackKey(true)](https://github.com/libgdx/libgdx/wiki/Back-and-menu-key-catching) at the start of your game. Then you should be able to detect the back key with FlxG.keys.justPressed("BACK");.

**Comment by peterwilli** [comment]
@moly awesome! That worked!
