### ISSUE TITLE
Render off-screen objects as safe-zone

### ISSUE THREAD

**Issue by peterwilli** [flixel-gdx/flixel-gdx#84]
Sorry it's me again ;)
We have an issue where we use FlxCamera using `super(480, 800, MenuState.class, 1, 60, 60, true, FlxCamera.FILL_X);`

The problem is that what I want is to render a few elements full-width (as in: the width of the window, not the width of the game) to create some sort of safezone that is rendered instead of black bars.
In short I try to replicate LibGDX's ExtendViewport behaviour (see: http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/viewport/ExtendViewport.html)

I've been spending the whole day hacking around - things I have tried (and failed):

- Get the current screen width and set the game size to that screen width (in the super call)
   - Worked on paper, but was incredibly hard to implement because android Display object wasnt initialized yet so I had to create my own version of FlxAndroidApplication to pull that off.

- Using ExtendViewport from libgdx and set it to FlxG.camera.getCamera()
  - Did not work as it would on LibGDX :(

- Try to set the Camera bounds wider

So I'm a little out of ideas right now and was hoping you guys could help. Thanks!

**Comment by moly** [comment]
Hi,

It sounds like you're trying to do something similar to the Mode demo. Have a look at the first two lines of create() in https://github.com/flixel-gdx/flixel-gdx-examples/blob/master/flixel-examples-core/src/org/flixel/examples/mode/MenuState.java.

It sets the game width to match the ratio of the screen, then resets the cameras so they use the new values.

**Comment by peterwilli** [comment]
@moly you are my saviour! I cant thank you enough!
Every year from this day on, on 13th of April we will take a moment of silence for 2 minutes to remember Moly the Brave - who solved a bug even the most brilliant minds in the kingdom couldn't solve. He will be honored for life and remembered for ever.
