### ISSUE TITLE
Clearing pixmap graphics

### ISSUE THREAD

**Issue by Dimitri0xff** [flixel-gdx/flixel-gdx#95]
Hi,
I have a sprite and it has a line drawn on transparent background with makegraphic() then drawline().
I want to clear the pixmap to redraw the line in a different position.
fill(0) did not work, so my closest attempt is:
```java
private void clear() {
	Pixmap.setBlending(Pixmap.Blending.SourceOver);
	Pixmap.setFilter(Pixmap.Filter.NearestNeighbour);
	TextureData textureData = null;
	if(_newTextureData != null)
		textureData = _newTextureData;
	else
		textureData = _pixels.getTexture().getTextureData();

	if(!textureData.isPrepared())
		textureData.prepare();

	Pixmap pixmap = textureData.consumePixmap();
	pixmap.setColor(Color.CLEAR);
	pixmap.fill();

	_newTextureData = new ManagedTextureData(pixmap);
}
```

It works on desktop, but does not work on HTML5.... :(
So how I do this?
An ok workaround would be to dispose the pixmap and create a new one with makegraphic, how can I do that?

**Comment by Dimitri0xff** [comment]
Or is it a libgdx issue? Then I submit it there..

**Comment by WingEraser** [comment]
Try this without using flixel-gd and see whether it works in HTML5 or not.
You can expect a lot of issues with GWT :disappointed:

**Comment by Dimitri0xff** [comment]
It works with Blending set to None.
