### ISSUE TITLE
Hi，Any plan to update this project ?

### ISSUE THREAD

**Issue by tianqiujie** [flixel-gdx/flixel-gdx#99]
Hi，Any plan to update this project ?

**Comment by robrtsql** [comment]
Hi tian,

Sorry, i don't think i plan on doing any more work on it.

Good luck in your game dev endeavors!

**Comment by tianqiujie** [comment]
OK

**Comment by robrtsql** [comment]
Oh my gosh!

I thought this was a different project.

Sorry. I am not the maintainer of this project. I take back my earlier
message.

Sorry!

**Comment by moly** [comment]
Hi,

I don't have any plans for major feature updates at the moment, but I will try to respond to bugs and other minor maintenance. Was there something  you wanted updating in particular?

**Comment by tianqiujie** [comment]
OH, I have find library called haxeflixel. very powerful. it is based on flixel.  http://haxeflixel.com/
